# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "google"
name = "Google"
url = "https://www.google.com"
[main.params]
icon = "home"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/lostinbreezes"

[social.params]
icon = "brand-github"


