# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "mail"
name = "Mail"
url = "<a href="mailto:lostinbreezes@gmail.com">"
[main.params]
icon = "mail"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/lostinbreezes"

[social.params]
icon = "brand-github"


